# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d55c2eaca57e08e4b06c83bc71fe2852c2b1f1c3df6d6569cd25343701d2aaefc1c9beeaaa68e850accf3b7c7571f5aaa9c9dbf3987c9a67e9f6fe24fbca7f2

test:
  secret_key_base: f61cfb6ab6b930fa1690f10da09009e301cea75c67c253b81667921ea5776770cf8b50fed42f1b74d4e3f24270635505bd00f737c9f0c88883f14b7892a77860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
